### ISSUE TITLE
error with metator host command 

### ISSUE THREAD

**Issue by meltzj** [koszullab/metaTOR#18]
Hi there,

I'm trying to use the metator host command after running metator. 
metator host --network=/path/to/network.txt --binning=/path/to/binning.txt --mges=/path/to/list_of_mges.txt --contig-data=/path/to/final/contig_data_final.txt

where network.txt, binning.txt  and contig_data_final.txt are the output files after running metator pipeline.

This is the following error I get:
INFO :: 
---

Traceback (most recent call last):
  File "/srv/scratch/z5116142/miniconda3/envs/metator_1/bin/metator", line 8, in <module>
    sys.exit(main())
  File "/srv/scratch/z5116142/miniconda3/envs/metator_1/lib/python3.10/site-packages/metator/main.py", line 63, in main
    command.execute()
  File "/srv/scratch/z5116142/miniconda3/envs/metator_1/lib/python3.10/site-packages/metator/commands.py", line 1454, in execute
    mth.host_detection(
  File "/srv/scratch/z5116142/miniconda3/envs/metator_1/lib/python3.10/site-packages/metator/host.py", line 280, in host_detection
    count = sub.getBinScore()
  File "/srv/scratch/z5116142/miniconda3/envs/metator_1/lib/python3.10/site-packages/metator/host.py", line 132, in getBinScore
    if score >= self.threshold:
TypeError: '>=' not supported between instances of 'float' and 'str'

Any suggestions?

**Comment by mmarbout** [comment]
Hi .
We do not often use the metator host command and rather use the whole pipeline metator mge to directly bin mge-contig and then assign their host(s). I have reproduced your error and will try to fix the problem in a next release of metator. For the moment, you can use the metator mge command that works without problems from my side.

Martial

**Comment by meltzj** [comment]
Hi there! Just checking in to see how you guys are going with this! Any updates?

**Comment by chenolaf** [comment]
I have the same trouble,Any updates?
